# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-06-09 11:48
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SuppliedInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='物资名称')),
                ('unit', models.CharField(max_length=5, verbose_name='单位')),
                ('specification', models.CharField(max_length=5, verbose_name='规格')),
                ('number', models.IntegerField(default=1, verbose_name='数量')),
                ('price', models.IntegerField(default=0, verbose_name='借用价格')),
                ('is_lend', models.BooleanField(default=False, verbose_name='是否可借用')),
            ],
            options={
                'verbose_name': '物资详情信息',
                'verbose_name_plural': '物资详情信息',
            },
        ),
        migrations.CreateModel(
            name='SuppliedLend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='借用物资名称')),
                ('specification', models.CharField(max_length=5, verbose_name='借用规格')),
                ('number', models.IntegerField(default=1, verbose_name='借用数量')),
                ('lend_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='借用时间')),
                ('return_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='归还时间')),
                ('organization', models.CharField(max_length=50, verbose_name='借用组织')),
                ('mobile', models.CharField(max_length=11, verbose_name='联系方式')),
                ('submit_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='提交时间')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户User')),
            ],
            options={
                'verbose_name': '借用详情表',
                'verbose_name_plural': '借用详情表',
            },
        ),
    ]
