# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-06-08 23:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supplied', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lendtable',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户User'),
        ),
    ]
