# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-06-09 11:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplied', '0002_auto_20190609_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suppliedlend',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='suppliedlend',
            name='organization',
        ),
    ]
