# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-06-09 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplied', '0003_auto_20190609_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliedlend',
            name='is_check',
            field=models.BooleanField(default=False, verbose_name='是否通过'),
        ),
    ]
