# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-06-17 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplied', '0004_suppliedlend_is_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliedlend',
            name='id_lend',
            field=models.BooleanField(default=False, verbose_name='是否可借'),
        ),
        migrations.AlterField(
            model_name='suppliedlend',
            name='is_check',
            field=models.BooleanField(default=False, verbose_name='是否已审核'),
        ),
    ]
