# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-06-17 17:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplied', '0005_auto_20190617_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suppliedlend',
            old_name='id_lend',
            new_name='is_lend',
        ),
    ]
