# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-06-24 09:36
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supplied', '0006_auto_20190617_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuppliedComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200, verbose_name='评论')),
                ('star', models.IntegerField(default=5, verbose_name='星级')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('name', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='supplied.SuppliedInfo', verbose_name='物资名字')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户User')),
            ],
        ),
    ]
