# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-06-24 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplied', '0007_suppliedcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suppliedcomment',
            options={'verbose_name': '物资评论表', 'verbose_name_plural': '物资评论表'},
        ),
        migrations.RemoveField(
            model_name='suppliedcomment',
            name='star',
        ),
        migrations.AddField(
            model_name='suppliedinfo',
            name='star',
            field=models.IntegerField(default=5, verbose_name='星级'),
        ),
    ]
