# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-06-08 05:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplied', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=50, verbose_name='借用组织')),
                ('lend_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='借用时间')),
                ('return_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='归还时间')),
                ('is_ok', models.BooleanField(default=False, verbose_name='是否可借用')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplied.LendTable', verbose_name='借用物资名称')),
            ],
            options={
                'verbose_name': '借用审核表',
                'verbose_name_plural': '借用审核表',
            },
        ),
    ]
